// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrok8riILeBJaGXfeiSGmLoGayrPFEtGg',
    appId: '1:834399039662:web:0d0445eb1a10af0fc03d3f',
    messagingSenderId: '834399039662',
    projectId: 'bancacreditosapp',
    authDomain: 'bancacreditosapp.firebaseapp.com',
    databaseURL: 'https://bancacreditosapp-default-rtdb.firebaseio.com',
    storageBucket: 'bancacreditosapp.appspot.com',
    measurementId: 'G-RWPXNPLMYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLs_aJ2tMoyE-8-u981ReEIxk76nkNOFA',
    appId: '1:834399039662:android:2c18e60f1c4e4020c03d3f',
    messagingSenderId: '834399039662',
    projectId: 'bancacreditosapp',
    databaseURL: 'https://bancacreditosapp-default-rtdb.firebaseio.com',
    storageBucket: 'bancacreditosapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqvmWOFJgBigAfShmoOlWFWixuMIArRtE',
    appId: '1:834399039662:ios:8b5a21973b5dfaf5c03d3f',
    messagingSenderId: '834399039662',
    projectId: 'bancacreditosapp',
    databaseURL: 'https://bancacreditosapp-default-rtdb.firebaseio.com',
    storageBucket: 'bancacreditosapp.appspot.com',
    iosBundleId: 'com.example.bancaCreditosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqvmWOFJgBigAfShmoOlWFWixuMIArRtE',
    appId: '1:834399039662:ios:76f3741d8925b2c9c03d3f',
    messagingSenderId: '834399039662',
    projectId: 'bancacreditosapp',
    databaseURL: 'https://bancacreditosapp-default-rtdb.firebaseio.com',
    storageBucket: 'bancacreditosapp.appspot.com',
    iosBundleId: 'com.example.bancaCreditosApp.RunnerTests',
  );
}
