import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class InteractiveDataTable extends StatelessWidget {
  const InteractiveDataTable({super.key});

  @override
  Widget build(BuildContext context) {
    double screenWidth = MediaQuery.of(context).size.width;
    double screenHeight = MediaQuery.of(context).size.height;

    return Container(
      color: Colors.white,
      margin: const EdgeInsets.all(10),
      child: ConstrainedBox(
        constraints: const BoxConstraints.expand(width: 900),
        child: InteractiveViewer(
          constrained: false,
          child: DataTable(
            columns: const <DataColumn>[
              DataColumn(label: Text('Saldo inicial')),
              DataColumn(label: Text('Número de la cuota')),
              DataColumn(label: Text('Cuota')),
              DataColumn(label: Text('Interés')),
              DataColumn(label: Text('Abono a capital')),
              DataColumn(label: Text('Saldo del período')),
            ],
            rows: const <DataRow>[
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
              DataRow(cells: <DataCell>[
                DataCell(Text('Row 1, Col 1')),
                DataCell(Text('Row 1, Col 2')),
                DataCell(Text('Row 1, Col 3')),
                DataCell(Text('Row 1, Col 4')),
                DataCell(Text('Row 1, Col 5')),
                DataCell(Text('Row 1, Col 6')),
              ]),
            ],
          ),
        ),
      ),
    );
  }
}
